
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


sensor:
  - platform: rest
    name: Customization Engine Sensor
    resource: http://10.11.22.31:5000  # Replace with the host machine's IP address
    method: GET
    headers:
      Content-Type: application/json
    value_template: '{{ value }}'
    scan_interval: 60
  - platform: rest
    name: Voice Recognition Engine Sensor
    resource: http://10.11.22.31:5001  # Replace with the host machine's IP address
    method: GET
    headers:
      Content-Type: application/json
    value_template: '{{ value }}'
    scan_interval: 60


    